### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by bethleha**
@paambaati Please review.

### CODE REVIEW

**Comment by bethleha** [comment]
@Vasanth-Indix or @paambaati The 3 enhancements are completed. Please review and merge.

**Comment by Vasanth-Indix** [comment]
@bethleha : I think, by default all the links need to open in new tab. Only those where `target=_self`, let us make it open in the same tab.
Possible to change?

**Comment by paambaati** [comment]
> Only those where target=_self, let us make it open in the same tab.

@Vasanth-Indix I'm not sure that is possible, because standard markdown doesn't let us use attributes. For now, I'm okay with letting all hyperlinks in our YAML open in a new tab.

**Comment by Vasanth-Indix** [comment]
@paambaati: Already merged? The reason I asked is that I had to added `target=_blank` to every link mentioned in that yaml. If that's the default behavior, can we make really default for all the links in the YAML?

**Comment by paambaati** [comment]
> can we make really default for all the links in the YAML?

That's what Raja's PR does. @bethleha Is that correct?

**EDIT:** Oh wait, I didn't see the giant YAML patchset because it didn't load. @bethleha Can you modify the showdown extension so that it just adds the `_target=blank` to ALL hyperlinks without any `{:target}` qualifier?

**Pull request merged**
